name: NSFS Ceph S3 Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  nsfs-ceph-s3-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout noobaa-core
        uses: actions/checkout@v3
        with:
          repository: 'noobaa/noobaa-core'
          path: 'noobaa-core'

      - name: Run NSFS Ceph s3-tests
        run: |
          set -x
          echo "mocking NSFS Ceph s3-tests"
